# .nosana-ci.yml
nosana:
  description: Build, Test and Deploy dApps!

global:
  image: alpine
  trigger:
    push:
      branches:
        - main

jobs:
  - name: build
    commands:
      - echo "building 123..."
      - npm ci
      - npx hardhat compile
 

  - name: test
    commands:
      - echo "testing..."


  - name: deploy
    commands:
      - echo "deploying..."
