# .nosana-ci.yml
nosana:
  description: Build, Test and Deploy dApps!

global:
  image: node:16
  trigger:
    push:
      branches:
        - main

jobs:
  - name: build
    commands:
      - echo "building 123..."
      - npm i
      - npx hardhat compile
    artifacts:
      - name: node_modules
 

  - name: test
    commands:
      - echo "testing..."
      - npx hardhat test
    resources:
      - name: node_modules


  - name: deploy
    commands:
      - echo "deploying..."
